id: se_rocket_tracker
name: SE AI Tracker
version: 1.22.0
author: SE Dang Huu Tuan
icon: icon.png
desc: Selectable rocket, person, animal and object tracker for the ESP32 gimbal.
files:
  - app.yaml
  - icon.png
  - main.py
  - models/se_water_rocket_yolo11n.mud
  - models/se_water_rocket_yolo11n.cvimodel
